//! OpenAPI document + interactive docs (`DESIGN.md` §10.6 admin surface, §17).
//!
//! The spec is authored by hand as a `serde_json::Value` (OpenAPI 3.0.3) rather than generated by
//! `utoipa`. The contract (`DESIGN.md` §10.6) requires the endpoints to be documented and served,
//! not a specific generator; a hand-written doc is deterministic, adds no dependencies, and stays
//! readable for a stable admin API. `/docs` serves a Scalar page that renders `/openapi.json`. All
//! `/admin/*` operations are secured by the admin bearer token (`DESIGN.md` §16).

use serde_json::{Value, json};

/// The OpenAPI 3.0.3 document for the proxy's admin + operational surface.
pub fn openapi_spec() -> Value {
    // Shared pieces.
    let unauthorized = json!({
        "description": "Unauthorized — missing or invalid admin token.",
        "content": { "application/json": { "schema": { "$ref": "#/components/schemas/Error" } } }
    });
    let op = |summary: &str, desc: &str, tag: &str, body: Option<Value>| -> Value {
        let mut v = json!({
            "tags": [tag],
            "summary": summary,
            "description": desc,
            "security": [{ "adminBearer": [] }],
            "responses": {
                "200": { "description": desc },
                "401": unauthorized.clone(),
                "500": {
                    "description": "Storage error.",
                    "content": { "application/json": { "schema": { "$ref": "#/components/schemas/Error" } } }
                }
            }
        });
        if let Some(b) = body {
            v["requestBody"] = b;
        }
        v
    };

    json!({
        "openapi": "3.0.3",
        "info": {
            "title": "unillm-proxy",
            "version": "1.0.0",
            "description": "Universal bidirectional LLM translator proxy. Admin/management surface (`DESIGN.md` §10.6) plus liveness/readiness/metrics.",
            "license": { "name": "MIT OR Apache-2.0" }
        },
        "servers": [{ "url": "/" }],
        "tags": [
            { "name": "keys", "description": "Virtual-key management (§13.1)" },
            { "name": "models", "description": "Model catalog (§13.2)" },
            { "name": "routes", "description": "Routing rules (§13.3)" },
            { "name": "usage", "description": "Usage analytics (§13.5)" },
            { "name": "logs", "description": "Request logs (§13.5)" },
            { "name": "cache", "description": "Response cache (§7.4)" },
            { "name": "system", "description": "Health, readiness, metrics" }
        ],
        "paths": {
            "/admin/keys": {
                "post": op("Create virtual key", "Create a key; the secret is returned exactly once.", "keys",
                    Some(json!({ "required": true, "content": { "application/json": { "schema": { "$ref": "#/components/schemas/CreateKeyRequest" } } } }))),
                "get": op("List virtual keys", "List keys (secrets never returned); optional tenant filter.", "keys", None)
            },
            "/admin/keys/{id}": {
                "patch": op("Update virtual key", "Partial update of a key (scopes/limits/revocation).", "keys",
                    Some(json!({ "required": true, "content": { "application/json": { "schema": { "$ref": "#/components/schemas/UpdateKey" } } } }))),
                "delete": op("Revoke virtual key", "Mark a key revoked (sets revoked_at).", "keys", None)
            },
            "/admin/models": {
                "post": op("Upsert model", "Insert or update a model-catalog row by (provider, native_model).", "models",
                    Some(json!({ "required": true, "content": { "application/json": { "schema": { "$ref": "#/components/schemas/ModelInput" } } } }))),
                "get": op("List models", "List the model catalog.", "models", None)
            },
            "/admin/models/{provider}/{native_model}": {
                "delete": op("Delete model", "Remove a model by (provider, native_model).", "models", None)
            },
            "/admin/routes": {
                "post": op("Upsert route", "Insert or replace a routing rule by (alias, tenant_id).", "routes",
                    Some(json!({ "required": true, "content": { "application/json": { "schema": { "$ref": "#/components/schemas/RouteInput" } } } }))),
                "get": op("List routes", "List routing rules; optional tenant filter.", "routes", None)
            },
            "/admin/routes/{alias}": {
                "delete": op("Delete route", "Remove a route by alias (and optional tenant).", "routes", None)
            },
            "/admin/usage": {
                "get": op("Usage summary", "Aggregated usage/cost, optionally filtered and grouped.", "usage", None)
            },
            "/admin/logs": {
                "get": op("Request logs", "Paginated request logs, newest first.", "logs", None)
            },
            "/admin/cache/invalidate": {
                "post": op("Invalidate cache", "Flush cached responses by scope/key_hash (both empty = all).", "cache",
                    Some(json!({ "required": true, "content": { "application/json": { "schema": { "$ref": "#/components/schemas/InvalidateRequest" } } } })))
            },
            "/health": { "get": op("Liveness", "Always 200 if the process is up.", "system", None) },
            "/ready":  { "get": op("Readiness", "200 if at least one upstream provider is configured.", "system", None) },
            "/metrics": { "get": op("Prometheus metrics", "Prometheus text exposition (§17).", "system", None) }
        },
        "components": {
            "securitySchemes": {
                "adminBearer": { "type": "http", "scheme": "bearer", "description": "Admin token (UNILLM_ADMIN_TOKEN), distinct from data-plane virtual keys." }
            },
            "schemas": {
                "Error": {
                    "type": "object",
                    "properties": { "error": { "$ref": "#/components/schemas/ErrorBody" } },
                    "required": ["error"]
                },
                "ErrorBody": {
                    "type": "object",
                    "properties": {
                        "kind": { "type": "string" },
                        "message": { "type": "string" }
                    },
                    "required": ["kind", "message"]
                },
                "CreateKeyRequest": {
                    "type": "object",
                    "required": ["tenant_id"],
                    "properties": {
                        "tenant_id": { "type": "string", "format": "uuid" },
                        "scopes": { "type": "array", "items": { "type": "string" }, "default": [] },
                        "model_allowlist": { "type": "array", "items": { "type": "string" } },
                        "budget_daily_tokens": { "type": "integer", "format": "int64" },
                        "rpm": { "type": "integer", "format": "int32" },
                        "tpm": { "type": "integer", "format": "int64" },
                        "max_concurrency": { "type": "integer", "format": "int32" },
                        "expires_at": { "type": "string", "format": "date-time" }
                    }
                },
                "CreateKeyResponse": {
                    "type": "object",
                    "properties": {
                        "id": { "type": "string", "format": "uuid" },
                        "key_id": { "type": "string" },
                        "key": { "type": "string", "description": "The secret, shown once." }
                    },
                    "required": ["id", "key_id", "key"]
                },
                "UpdateKey": {
                    "type": "object",
                    "properties": {
                        "scopes": { "type": "array", "items": { "type": "string" } },
                        "model_allowlist": { "type": "array", "items": { "type": "string" } },
                        "budget_daily_tokens": { "type": "integer", "format": "int64" },
                        "rpm": { "type": "integer", "format": "int32" },
                        "tpm": { "type": "integer", "format": "int64" },
                        "max_concurrency": { "type": "integer", "format": "int32" },
                        "expires_at": { "type": "string", "format": "date-time" },
                        "revoked": { "type": "boolean" }
                    }
                },
                "ModelInput": {
                    "type": "object",
                    "required": ["provider", "native_model", "display_name"],
                    "properties": {
                        "provider": { "type": "string" },
                        "native_model": { "type": "string" },
                        "display_name": { "type": "string" },
                        "context_window": { "type": "integer", "format": "int32" },
                        "max_output": { "type": "integer", "format": "int32" },
                        "price_in": { "type": "number", "format": "double", "description": "Per 1M tokens (USD)." },
                        "price_out": { "type": "number", "format": "double" },
                        "price_cache_read": { "type": "number", "format": "double" },
                        "enabled": { "type": "boolean", "default": true }
                    }
                },
                "RouteInput": {
                    "type": "object",
                    "required": ["alias", "provider", "native_model"],
                    "properties": {
                        "alias": { "type": "string" },
                        "tenant_id": { "type": "string", "format": "uuid" },
                        "provider": { "type": "string" },
                        "native_model": { "type": "string" },
                        "fallback": { "type": "array", "items": { "$ref": "#/components/schemas/FallbackTarget" } },
                        "priority": { "type": "integer", "format": "int32", "default": 0 },
                        "enabled": { "type": "boolean", "default": true }
                    }
                },
                "FallbackTarget": {
                    "type": "object",
                    "required": ["provider", "native_model"],
                    "properties": {
                        "provider": { "type": "string" },
                        "native_model": { "type": "string" }
                    }
                },
                "InvalidateRequest": {
                    "type": "object",
                    "properties": {
                        "scope": { "type": "string", "description": "Virtual-key id; omit for all scopes." },
                        "key_hash": { "type": "string", "description": "Cache key hash; omit for all hashes." }
                    }
                },
                "InvalidateResponse": {
                    "type": "object",
                    "properties": { "invalidated": { "type": "integer", "format": "int64" } },
                    "required": ["invalidated"]
                }
            }
        }
    })
}

/// The Scalar interactive-docs HTML, which renders `/openapi.json`.
pub fn docs_html() -> &'static str {
    r#"<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>unillm-proxy · API docs</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <script id="api-reference" data-url="/openapi.json"></script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>
"#
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn spec_is_valid_openapi_with_admin_paths() {
        let spec = openapi_spec();
        assert_eq!(spec["openapi"], "3.0.3");
        let paths = spec["paths"].as_object().unwrap();
        // The core admin surface is documented.
        for p in [
            "/admin/keys",
            "/admin/keys/{id}",
            "/admin/models",
            "/admin/models/{provider}/{native_model}",
            "/admin/routes",
            "/admin/routes/{alias}",
            "/admin/usage",
            "/admin/logs",
            "/admin/cache/invalidate",
            "/health",
            "/ready",
            "/metrics",
        ] {
            assert!(paths.contains_key(p), "missing path {p}");
        }
        // Admin operations declare the bearer security scheme.
        assert_eq!(
            spec["paths"]["/admin/keys"]["post"]["security"][0]["adminBearer"],
            json!([])
        );
        // Component schemas referenced by request bodies exist.
        assert!(spec["components"]["schemas"]["CreateKeyRequest"].is_object());
        assert!(spec["components"]["schemas"]["InvalidateRequest"].is_object());
        assert!(spec["components"]["securitySchemes"]["adminBearer"].is_object());
    }

    #[test]
    fn docs_html_references_spec() {
        let html = docs_html();
        assert!(html.contains("data-url=\"/openapi.json\""));
    }
}
