#!/usr/bin/env bash
# unillm-proxy bootstrap: generate local secrets into `.env`, optionally start Postgres,
# and build + run the proxy. Idempotent — safe to re-run.
#
#   scripts/init.sh                # generate .env (if missing) + print next steps
#   scripts/init.sh --run          # also build + run the proxy
#   scripts/init.sh --postgres     # start Postgres via docker compose first
#   scripts/init.sh --postgres --run
set -euo pipefail

cd "$(dirname "$0")/.."
ENV_FILE=.env

rand() { openssl rand -hex "${1:-16}"; }

# --- 1. ensure .env exists with generated secrets ---
if [[ -f "$ENV_FILE" ]]; then
  echo "→ $ENV_FILE already exists; keeping it."
else
  echo "→ generating $ENV_FILE with fresh local secrets"
  {
    echo "# Local dev secrets — generated by scripts/init.sh. DO NOT COMMIT."
    echo "UNILLM_KEY_PEPPER=$(rand 32)"
    echo "UNILLM_ADMIN_TOKEN=$(rand 16)"
    echo "UNILLM_SEED_KEY=sk-unill-dev-$(rand 8)"
    echo
    echo "# Enable at least one upstream (else /ready = 503, no backend):"
    echo "# UNILLM_PROV_OPENAI_KEY="
    echo "# UNILLM_PROV_ANTHROPIC_KEY="
    echo "# UNILLM_PROV_OPENROUTER_KEY="
    echo "# UNILLM_PROV_DEEPSEEK_KEY="
    echo
    echo "UNILLM_DATABASE_URL=sqlite:unillm.db"
    echo "# UNILLM_CACHE_ENABLED=true"
    echo "# UNILLM_CACHE_TTL=300"
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  echo "  written (mode 600). Edit it to add an upstream key, then re-run."
fi

# --- 2. load .env into this process (KEY=VALUE lines only) ---
# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a

echo
echo "  data-plane seed key : ${UNILLM_SEED_KEY:-<unset>}"
echo "  admin token         : ${UNILLM_ADMIN_TOKEN:-<unset>}"
echo "  database            : ${UNILLM_DATABASE_URL:-sqlite:unillm.db}"
echo

# --- 3. optional: start Postgres ---
WANT_PG=0; WANT_RUN=0
for arg in "$@"; do
  case "$arg" in
    --postgres) WANT_PG=1;;
    --run)      WANT_RUN=1;;
    *) echo "unknown flag: $arg" >&2; exit 2;;
  esac
done

if [[ "$WANT_PG" -eq 1 ]]; then
  echo "→ starting Postgres (docker compose up -d postgres)"
  docker compose up -d postgres
  export UNILLM_DATABASE_URL=postgres://unillm:unillm@localhost:5432/unillm
fi

# --- 4. warn if no upstream is configured ---
if [[ -z "${UNILLM_PROV_OPENAI_KEY:-}${UNILLM_PROV_ANTHROPIC_KEY:-}${UNILLM_PROV_OPENROUTER_KEY:-}${UNILLM_PROV_DEEPSEEK_KEY:-}" ]]; then
  echo "⚠️  No UNILLM_PROV_*_KEY set in $ENV_FILE — /ready will be 503 and data-plane calls have no backend."
  echo "    Add one upstream key to $ENV_FILE, then re-run with --run."
  echo
fi

# --- 5. optional: build + run ---
if [[ "$WANT_RUN" -eq 1 ]]; then
  echo "→ cargo run -p unillm-proxy  (Ctrl-C to stop)"
  echo "    then: curl -s localhost:8080/health  ;  open http://localhost:8080/docs"
  echo
  exec cargo run -p unillm-proxy
else
  cat <<EOF
Next:
  scripts/init.sh --run          # build + run the proxy
  scripts/init.sh --postgres     # start Postgres first (uses UNILLM_DATABASE_URL=postgres://...)

Once running:
  curl -s localhost:8080/health
  open http://localhost:8080/docs        # Scalar admin-API docs (web UI)
  curl -s localhost:8080/metrics | head  # Prometheus

Call the data plane with the seed key above:
  curl -s localhost:8080/v1/chat/completions \\
    -H "authorization: Bearer \$UNILLM_SEED_KEY" \\
    -H "content-type: application/json" \\
    -d '{"model":"gpt-4o","messages":[{"role":"user","content":"hi"}]}'
EOF
fi
